use_frameworks!

platform :ios, '8.0'

target 'ZYANDXXFrame_Example' do
  pod 'ZYANDXXFrame', :path => '../'

  target 'ZYANDXXFrame_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
